### ISSUE TITLE
Error on command npm run degiro && cat porto.degiro.pine

### ISSUE THREAD

**Issue by coacheric** [topscoder/degiro-tradingview#3]
Dear sir/madam
I followed the manual but got stuck on the command npm run degiro && cat porto.degiro.pine
This is the error, i already disabled 2FA, what am i missing.
Any ideas?
With regards,
Eric

[+] Login to degiro account xxxx...
FetchError: invalid json response body at https://trader.degiro.nl/myracloud-blocked/?xxxxxxxxxxxxx  reason: Unexpected token < in JSON at position 0
    at /home/xxxx/degiro-tradingview/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'invalid-json'
}

**Comment by topscoder** [comment]
API calls were blocked by CloudFlare. I pushed a fix and released a new version (2024.8.1).

Do a `git pull` and a `npm install` in the `degiro-tradingview` directory to get the latest version.
